---
openapi: 3.0.0
info:
  title: Sentiment Analysis API
  description: Binary classification of sentiment in a given text using count vectorizer and logistic regression
  contact:
    email: mrun@rane.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/MRUNMAYEERANE17/test_1/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: sentiment_classification
  description: Finds sentiment of the text
paths:
  /sentiment:
    get:
      tags:
      - sentiment_classification
      summary: homepage
      description: prints Predict the sentiment of the text!
      operationId: UI
      responses:
        "200":
          description: Successfull Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/predict'
  /classify:
    post:
      tags:
      - sentiment_classification
      summary: sentiment classification
      description: predicting sentiment of the text
      operationId: finds sentiment of the text
      parameters:
      - name: Text
        in: query
        description: Enter text for predicting sentiment!
        required: false
        style: form
        explode: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        "200":
          description: ' Success!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
components:
  schemas:
    output:
      type: object
      properties:
        item:
          type: string
          example: The sentiment of the text is Positive!
    predict:
      type: object
      properties:
        item:
          type: string
          example: Predict the sentiment of the text!
    input:
      type: object
      properties:
        item:
          type: string
          example: Had wonderful experience with this airlines!
